// Package router assembles the Gin engine: global middleware + routes.
// Adding a new module later = registering its routes here, nothing else.
package router

import (
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"

	"ymmo/internal/config"
	"ymmo/internal/handlers"
	"ymmo/internal/middleware"
	"ymmo/internal/repositories"
	"ymmo/internal/services"
	"ymmo/internal/validation"

	// Generated by `swag init` (run it before building — see README).
	_ "ymmo/docs"
)

// New builds the fully configured HTTP engine.
func New(cfg *config.Config, db *gorm.DB) *gin.Engine {
	if cfg.AppEnv == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	// Install custom validators (e.g. "phone") before any route binds input.
	validation.Register()

	r := gin.New()

	// Global middleware: structured logging + panic recovery.
	r.Use(gin.Logger(), gin.Recovery())

	// CORS so the Tailwind front-end (served from another origin during
	// development) can call the API.
	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:5173", "http://localhost:3000"},
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	// --- Health check (outside the versioned API) ---
	health := handlers.NewHealthHandler(db)
	r.GET("/health", health.Check)

	// --- Interactive API documentation (Swagger UI) ---
	// Available at http://localhost:8080/swagger/index.html
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// --- Dependency wiring (composition root) ---
	// Built once at startup and injected downwards.
	userRepo := repositories.NewUserRepository(db)
	roleRepo := repositories.NewRoleRepository(db)
	authService := services.NewAuthService(userRepo, roleRepo, cfg.JWTSecret)
	authHandler := handlers.NewAuthHandler(authService)

	userService := services.NewUserService(userRepo)
	userHandler := handlers.NewUserHandler(userService)

	permissionRepo := repositories.NewPermissionRepository(db)
	permissionService := services.NewPermissionService(permissionRepo)
	permissionHandler := handlers.NewPermissionHandler(permissionService)

	propertyRepo := repositories.NewPropertyRepository(db)
	propertyService := services.NewPropertyService(propertyRepo, userRepo)
	propertyHandler := handlers.NewPropertyHandler(propertyService)

	favoriteRepo := repositories.NewFavoriteRepository(db)
	favoriteService := services.NewFavoriteService(favoriteRepo, propertyRepo)
	favoriteHandler := handlers.NewFavoriteHandler(favoriteService)

	photoRepo := repositories.NewPhotoRepository(db)
	photoService := services.NewPhotoService(photoRepo, propertyRepo)
	photoHandler := handlers.NewPhotoHandler(photoService)

	conversationRepo := repositories.NewConversationRepository(db)
	messageService := services.NewMessageService(conversationRepo, userRepo)
	messageHandler := handlers.NewMessageHandler(messageService)

	visitRepo := repositories.NewVisitRepository(db)
	visitService := services.NewVisitService(visitRepo, propertyRepo)
	visitHandler := handlers.NewVisitHandler(visitService)

	meetingRepo := repositories.NewMeetingRepository(db)
	meetingService := services.NewMeetingService(meetingRepo)
	meetingHandler := handlers.NewMeetingHandler(meetingService)

	alertRepo := repositories.NewAlertRepository(db)
	alertService := services.NewAlertService(alertRepo)
	alertHandler := handlers.NewAlertHandler(alertService)

	saleRepo := repositories.NewSaleRepository(db)
	saleService := services.NewSaleService(saleRepo, propertyRepo, userRepo)
	saleHandler := handlers.NewSaleHandler(saleService)

	sellerAppRepo := repositories.NewSellerApplicationRepository(db)
	sellerAppService := services.NewSellerApplicationService(sellerAppRepo, userRepo, roleRepo)
	sellerAppHandler := handlers.NewSellerApplicationHandler(sellerAppService)

	// --- Versioned API ---
	api := r.Group("/api/v1")
	{
		api.GET("/ping", func(c *gin.Context) {
			c.JSON(200, gin.H{"message": "pong"})
		})

		auth := api.Group("/auth")
		{
			auth.POST("/register", authHandler.Register)
			auth.POST("/login", authHandler.Login)
			// Protected: requires a valid Bearer token.
			auth.GET("/me", middleware.Auth(cfg.JWTSecret), authHandler.Me)
		}

		properties := api.Group("/properties")
		{
			// Public catalogue: browse and view.
			properties.GET("", propertyHandler.List)
			properties.GET("/:id", propertyHandler.Get)

			// Favorites: any authenticated user (e.g. a buyer).
			properties.POST("/:id/favorites", middleware.Auth(cfg.JWTSecret), favoriteHandler.Add)
			properties.DELETE("/:id/favorites", middleware.Auth(cfg.JWTSecret), favoriteHandler.Remove)

			// Request a visit of this property.
			properties.POST("/:id/visits", middleware.Auth(cfg.JWTSecret), visitHandler.Request)

			// Create a listing: staff create a DRAFT they own; a SELLER submits
			// a PENDING_REVIEW listing that an agent validates afterwards.
			properties.POST("",
				middleware.Auth(cfg.JWTSecret),
				middleware.RequireRole("AGENT", "DIRECTOR", "HQ", "SELLER"),
				propertyHandler.Create,
			)

			// Management: staff only (valid token + internal role).
			staff := properties.Group("")
			staff.Use(
				middleware.Auth(cfg.JWTSecret),
				middleware.RequireRole("AGENT", "DIRECTOR", "HQ"),
			)
			{
				staff.PUT("/:id", propertyHandler.Update)
				staff.DELETE("/:id", propertyHandler.Delete)

				// Approve a seller submission (assign agent + publish).
				staff.POST("/:id/validate", propertyHandler.Validate)

				// Photo management for a property.
				staff.POST("/:id/photos", photoHandler.Add)
				staff.DELETE("/:id/photos/:photoId", photoHandler.Delete)
			}
		}

		// Current user's favorites list.
		api.GET("/favorites", middleware.Auth(cfg.JWTSecret), favoriteHandler.List)

		// Agent's own properties (all statuses) for the dashboard.
		meGroup := api.Group("/me")
		meGroup.Use(middleware.Auth(cfg.JWTSecret))
		{
			meGroup.GET("/properties", middleware.RequireRole("AGENT", "DIRECTOR", "HQ"), propertyHandler.ListMine)
		}

		// Management views. Roles are applied per route (directors manage
		// properties, IT administers users & access rights, etc.).
		mgmt := api.Group("/management")
		mgmt.Use(middleware.Auth(cfg.JWTSecret))
		{
			mgmt.GET("/properties", middleware.RequireRole("DIRECTOR", "HQ"), propertyHandler.ListAll)
			mgmt.GET("/pending-properties", middleware.RequireRole("AGENT", "DIRECTOR", "HQ"), propertyHandler.ListPending)
			mgmt.GET("/collaborators", middleware.RequireRole("DIRECTOR", "HQ", "IT"), userHandler.ListCollaborators)
			mgmt.GET("/users", middleware.RequireRole("IT", "HQ"), userHandler.ListAll)
			mgmt.GET("/permissions", middleware.RequireRole("IT", "HQ"), permissionHandler.GetMatrix)

			// Seller applications to review (agent/director/HQ).
			staffReview := middleware.RequireRole("AGENT", "DIRECTOR", "HQ")
			mgmt.GET("/seller-applications", staffReview, sellerAppHandler.ListPending)
			mgmt.POST("/seller-applications/:id/approve", staffReview, sellerAppHandler.Approve)
			mgmt.POST("/seller-applications/:id/reject", staffReview, sellerAppHandler.Reject)
		}

		// Become-seller requests: a buyer applies; an agent approves (above).
		sellerApps := api.Group("/seller-applications")
		sellerApps.Use(middleware.Auth(cfg.JWTSecret))
		{
			sellerApps.POST("", sellerAppHandler.Apply)
			sellerApps.GET("", sellerAppHandler.Mine)
		}

		// AI proxy: the browser talks to the Go API, which relays to the
		// internal Python service. The AI is never exposed publicly.
		aiProxy := handlers.NewAIProxy(cfg.AIBaseURL)
		aiGroup := api.Group("/ai")
		{
			// Price estimate and sale-delay prediction are shown on the
			// public property page.
			aiGroup.POST("/estimate", aiProxy)
			aiGroup.POST("/predict-delay", aiProxy)
			// Dashboards/analytics are staff-only.
			staffAI := aiGroup.Group("")
			staffAI.Use(middleware.Auth(cfg.JWTSecret), middleware.RequireRole("AGENT", "DIRECTOR", "HQ", "IT"))
			{
				staffAI.GET("/dashboard/kpis", aiProxy)
				staffAI.GET("/trends", aiProxy)
				staffAI.GET("/zones", aiProxy)
				staffAI.GET("/popular", aiProxy)
			}
		}

		// Messaging: any authenticated user, restricted to their own threads.
		messaging := api.Group("")
		messaging.Use(middleware.Auth(cfg.JWTSecret))
		{
			messaging.POST("/conversations", messageHandler.StartConversation)
			messaging.GET("/conversations", messageHandler.ListConversations)
			messaging.DELETE("/conversations/:id", messageHandler.Delete)
			messaging.POST("/conversations/:id/messages", messageHandler.SendMessage)
			messaging.GET("/conversations/:id/messages", messageHandler.GetMessages)
			messaging.GET("/messages/unread-count", messageHandler.UnreadCount)
		}

		// Visits: any authenticated participant manages their own.
		visits := api.Group("")
		visits.Use(middleware.Auth(cfg.JWTSecret))
		{
			visits.GET("/visits", visitHandler.List)
			visits.PATCH("/visits/:id", visitHandler.UpdateStatus)
		}

		// Meetings: internal. Listing/deleting is for the user's own meetings;
		// creating is staff only.
		meetings := api.Group("/meetings")
		meetings.Use(middleware.Auth(cfg.JWTSecret))
		{
			meetings.GET("", meetingHandler.List)
			meetings.DELETE("/:id", meetingHandler.Delete)

			staffMeetings := meetings.Group("")
			staffMeetings.Use(middleware.RequireRole("AGENT", "DIRECTOR", "HQ"))
			{
				staffMeetings.POST("", meetingHandler.Create)
			}
		}

		// Search alerts: any authenticated user manages their own.
		alerts := api.Group("/alerts")
		alerts.Use(middleware.Auth(cfg.JWTSecret))
		{
			alerts.POST("", alertHandler.Create)
			alerts.GET("", alertHandler.List)
			alerts.DELETE("/:id", alertHandler.Delete)
		}

		// Sale files: participants can read; only staff create/advance them.
		sales := api.Group("/sales")
		sales.Use(middleware.Auth(cfg.JWTSecret))
		{
			sales.GET("", saleHandler.List)
			sales.GET("/:id", saleHandler.Get)

			staffSales := sales.Group("")
			staffSales.Use(middleware.RequireRole("AGENT", "DIRECTOR", "HQ"))
			{
				staffSales.POST("", saleHandler.Create)
				staffSales.PATCH("/:id", saleHandler.Update)
			}
		}
	}

	return r
}
