// Package router assembles the Gin engine: global middleware + routes.
// Adding a new module later = registering its routes here, nothing else.
package router

import (
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"

	"ymmo/internal/config"
	"ymmo/internal/handlers"
	"ymmo/internal/middleware"
	"ymmo/internal/repositories"
	"ymmo/internal/services"
	"ymmo/internal/validation"

	// Generated by `swag init` (run it before building — see README).
	_ "ymmo/docs"
)

// New builds the fully configured HTTP engine.
func New(cfg *config.Config, db *gorm.DB) *gin.Engine {
	if cfg.AppEnv == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	// Install custom validators (e.g. "phone") before any route binds input.
	validation.Register()

	r := gin.New()

	// Global middleware: structured logging + panic recovery.
	r.Use(gin.Logger(), gin.Recovery())

	// CORS so the Tailwind front-end (served from another origin during
	// development) can call the API.
	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:5173", "http://localhost:3000"},
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	// --- Health check (outside the versioned API) ---
	health := handlers.NewHealthHandler(db)
	r.GET("/health", health.Check)

	// --- Interactive API documentation (Swagger UI) ---
	// Available at http://localhost:8080/swagger/index.html
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// --- Dependency wiring (composition root) ---
	// Built once at startup and injected downwards.
	userRepo := repositories.NewUserRepository(db)
	roleRepo := repositories.NewRoleRepository(db)
	authService := services.NewAuthService(userRepo, roleRepo, cfg.JWTSecret)
	authHandler := handlers.NewAuthHandler(authService)

	propertyRepo := repositories.NewPropertyRepository(db)
	propertyService := services.NewPropertyService(propertyRepo)
	propertyHandler := handlers.NewPropertyHandler(propertyService)

	favoriteRepo := repositories.NewFavoriteRepository(db)
	favoriteService := services.NewFavoriteService(favoriteRepo, propertyRepo)
	favoriteHandler := handlers.NewFavoriteHandler(favoriteService)

	photoRepo := repositories.NewPhotoRepository(db)
	photoService := services.NewPhotoService(photoRepo, propertyRepo)
	photoHandler := handlers.NewPhotoHandler(photoService)

	conversationRepo := repositories.NewConversationRepository(db)
	messageService := services.NewMessageService(conversationRepo, userRepo)
	messageHandler := handlers.NewMessageHandler(messageService)

	visitRepo := repositories.NewVisitRepository(db)
	visitService := services.NewVisitService(visitRepo, propertyRepo)
	visitHandler := handlers.NewVisitHandler(visitService)

	// --- Versioned API ---
	api := r.Group("/api/v1")
	{
		api.GET("/ping", func(c *gin.Context) {
			c.JSON(200, gin.H{"message": "pong"})
		})

		auth := api.Group("/auth")
		{
			auth.POST("/register", authHandler.Register)
			auth.POST("/login", authHandler.Login)
			// Protected: requires a valid Bearer token.
			auth.GET("/me", middleware.Auth(cfg.JWTSecret), authHandler.Me)
		}

		properties := api.Group("/properties")
		{
			// Public catalogue: browse and view.
			properties.GET("", propertyHandler.List)
			properties.GET("/:id", propertyHandler.Get)

			// Favorites: any authenticated user (e.g. a buyer).
			properties.POST("/:id/favorites", middleware.Auth(cfg.JWTSecret), favoriteHandler.Add)
			properties.DELETE("/:id/favorites", middleware.Auth(cfg.JWTSecret), favoriteHandler.Remove)

			// Request a visit of this property.
			properties.POST("/:id/visits", middleware.Auth(cfg.JWTSecret), visitHandler.Request)

			// Management: staff only (valid token + internal role).
			staff := properties.Group("")
			staff.Use(
				middleware.Auth(cfg.JWTSecret),
				middleware.RequireRole("AGENT", "DIRECTOR", "HQ"),
			)
			{
				staff.POST("", propertyHandler.Create)
				staff.PUT("/:id", propertyHandler.Update)
				staff.DELETE("/:id", propertyHandler.Delete)

				// Photo management for a property.
				staff.POST("/:id/photos", photoHandler.Add)
				staff.DELETE("/:id/photos/:photoId", photoHandler.Delete)
			}
		}

		// Current user's favorites list.
		api.GET("/favorites", middleware.Auth(cfg.JWTSecret), favoriteHandler.List)

		// Messaging: any authenticated user, restricted to their own threads.
		messaging := api.Group("")
		messaging.Use(middleware.Auth(cfg.JWTSecret))
		{
			messaging.POST("/conversations", messageHandler.StartConversation)
			messaging.GET("/conversations", messageHandler.ListConversations)
			messaging.POST("/conversations/:id/messages", messageHandler.SendMessage)
			messaging.GET("/conversations/:id/messages", messageHandler.GetMessages)
			messaging.GET("/messages/unread-count", messageHandler.UnreadCount)
		}

		// Visits: any authenticated participant manages their own.
		visits := api.Group("")
		visits.Use(middleware.Auth(cfg.JWTSecret))
		{
			visits.GET("/visits", visitHandler.List)
			visits.PATCH("/visits/:id", visitHandler.UpdateStatus)
		}
	}

	return r
}
