// Command api is the entry point of the Ymmo back-end.
package main

import (
	"context"
	"errors"
	"log"
	"net/http"
	"os/signal"
	"syscall"
	"time"

	"ymmo/internal/config"
	"ymmo/internal/database"
	"ymmo/internal/router"

	_ "ymmo/docs" // generated by `swag init`: registers the OpenAPI spec served at /swagger/doc.json
)

// @title           Ymmo API
// @version         1.0
// @description     REST API for the Ymmo real-estate platform.
// @BasePath        /api/v1

// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Type "Bearer" followed by a space and your JWT token.
func main() {
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config error: %v", err)
	}

	db, err := database.Connect(cfg)
	if err != nil {
		log.Fatalf("database error: %v", err)
	}
	log.Println("connected to MariaDB")

	srv := &http.Server{
		Addr:              ":" + cfg.AppPort,
		Handler:           router.New(cfg, db),
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		log.Printf("ymmo-api listening on %s (%s)", srv.Addr, cfg.AppEnv)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("server error: %v", err)
		}
	}()

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()
	<-ctx.Done()

	log.Println("shutting down...")
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Fatalf("forced shutdown: %v", err)
	}

	if sqlDB, err := db.DB(); err == nil {
		_ = sqlDB.Close()
	}
	log.Println("stopped cleanly")
}
